// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxqyjuonvxiccrrjxtqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4cXlqdW9udnhpY2Nycmp4dHF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NDQ5NDIsImV4cCI6MjA2OTAyMDk0Mn0.kOvtvTRNWxDU5-l-L5KcVWlhYlha3rnCjnpXnH-PcNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});